# Generated by Django 5.0.6 on 2025-10-26 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_marca_alter_movimientoinventario_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='modelo',
            field=models.CharField(blank=True, help_text='Ej: G502 Hero, Viper Mini, etc.', max_length=100),
        ),
    ]
