# Generated by Django 5.0.6 on 2025-10-26 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_producto_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='caracteristicas',
            field=models.TextField(blank=True, help_text='Características adicionales del producto, una por línea.'),
        ),
    ]
