# Generated by Django 5.0.6 on 2025-11-01 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_banco', models.CharField(blank=True, help_text='Nombre del banco para transferencias o pagos QR.', max_length=100)),
                ('numero_cuenta', models.CharField(blank=True, help_text='Número de cuenta bancaria.', max_length=50)),
                ('nombre_titular', models.CharField(blank=True, help_text='Nombre del titular de la cuenta.', max_length=150)),
                ('documento_titular', models.CharField(blank=True, help_text='CI o NIT del titular de la cuenta.', max_length=20)),
                ('glosa_qr', models.CharField(blank=True, default='Pago de productos', help_text='Concepto o glosa que aparecerá en el QR.', max_length=100)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuración del Sistema',
            },
        ),
    ]
