# Generated by Django 5.0.6 on 2025-11-01 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['nombre'], name='clientes_cl_nombre_c231de_idx'),
        ),
    ]
