# Generated by Django 5.0.6 on 2025-11-01 22:16

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('moneda', models.CharField(default='BOB', max_length=10)),
                ('metodo', models.CharField(default='stripe', max_length=30)),
                ('estado', models.CharField(choices=[('creado', 'Creado'), ('aprobado', 'Aprobado'), ('fallido', 'Fallido'), ('reembolsado', 'Reembolsado')], db_index=True, default='creado', max_length=12)),
                ('referencia', models.CharField(blank=True, db_index=True, max_length=120)),
                ('idempotency_key', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='ventas.venta')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
